version: "3"

services:
  nginx-example:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ../:/www
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
  php-example:
    build: service-php
    volumes:
      - ../:/www
  mysql-example:
    image: mysql:5.7
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpassword"
      MYSQL_DATABASE: "mysqldbname"
    command: mysqld --sql_mode=""
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
